//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiMIRAI_Construcciones.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesPreventivos
    {
        public int idDetallesPreventivos { get; set; }
        public Nullable<int> idfRevisiones { get; set; }
        public Nullable<int> idfCategoriasPreventivas { get; set; }
        public string nombreParte { get; set; }
        public string estado { get; set; }
        public string comentarios { get; set; }
        public string observaciones { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public int numeroReporte { get; set; }
    
        public virtual CategoriasPreventivas CategoriasPreventivas { get; set; }
        public virtual Revisiones Revisiones { get; set; }
    }
}
