//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIMIRAI_Construcciones.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipos()
        {
            this.Lugares = new HashSet<Lugares>();
            this.QrEquipos = new HashSet<QrEquipos>();
            this.Recordatorios = new HashSet<Recordatorios>();
            this.Revisiones = new HashSet<Revisiones>();
        }
    
        public int idEquipos { get; set; }
        public string codigoArticulo { get; set; }
        public string nombreArticulo { get; set; }
        public string nombreComercial { get; set; }
        public string numIdentificador { get; set; }
        public string descripcion { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public Nullable<System.DateTime> fechadeRegistro { get; set; }
        public Nullable<int> idfUbicaciones { get; set; }
        public Nullable<int> idfUnidades { get; set; }
        public Nullable<int> idfEstatus { get; set; }
        public Nullable<int> idfTiposMaquinarias { get; set; }
    
        public virtual Estatus Estatus { get; set; }
        public virtual TiposMaquinarias TiposMaquinarias { get; set; }
        public virtual Ubicaciones Ubicaciones { get; set; }
        public virtual Unidades Unidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lugares> Lugares { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QrEquipos> QrEquipos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recordatorios> Recordatorios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Revisiones> Revisiones { get; set; }
    }
}
