//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIMIRAI_Construcciones.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lugares
    {
        public int idLugares { get; set; }
        public string nombreLugar { get; set; }
        public Nullable<int> idfEquipos { get; set; }
    
        public virtual Equipos Equipos { get; set; }
    }
}
