//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiMIRAI_Construcciones.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlmacenTAEPIEntities : DbContext
    {
        public AlmacenTAEPIEntities()
            : base("name=AlmacenTAEPIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoriasPreventivas> CategoriasPreventivas { get; set; }
        public virtual DbSet<DetallesPreventivos> DetallesPreventivos { get; set; }
        public virtual DbSet<Empresas> Empresas { get; set; }
        public virtual DbSet<Equipos> Equipos { get; set; }
        public virtual DbSet<Estatus> Estatus { get; set; }
        public virtual DbSet<Lugares> Lugares { get; set; }
        public virtual DbSet<Prioridades> Prioridades { get; set; }
        public virtual DbSet<QrEquipos> QrEquipos { get; set; }
        public virtual DbSet<Recordatorios> Recordatorios { get; set; }
        public virtual DbSet<Refacciones> Refacciones { get; set; }
        public virtual DbSet<Revisiones> Revisiones { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Tareas> Tareas { get; set; }
        public virtual DbSet<TiposMantenimientos> TiposMantenimientos { get; set; }
        public virtual DbSet<TiposMaquinarias> TiposMaquinarias { get; set; }
        public virtual DbSet<Ubicaciones> Ubicaciones { get; set; }
        public virtual DbSet<Unidades> Unidades { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
