//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIMIRAI_Construcciones.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QrEquipos
    {
        public int idQrEquipos { get; set; }
        public string claveQR { get; set; }
        public Nullable<int> idEquipos { get; set; }
    
        public virtual Equipos Equipos { get; set; }
    }
}
