//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIMIRAI_Construcciones.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recordatorios
    {
        public int idRecordatorios { get; set; }
        public Nullable<int> idfEquipos { get; set; }
        public Nullable<int> idfTareas { get; set; }
        public Nullable<int> idfUsuarios { get; set; }
        public Nullable<int> idfPrioridades { get; set; }
        public Nullable<int> idfTiposMantenimientos { get; set; }
        public byte[] recordarS_N { get; set; }
        public Nullable<System.DateTime> fechaRecordatorio { get; set; }
        public Nullable<int> numeroReporte { get; set; }
        public string descripcion { get; set; }
    
        public virtual Equipos Equipos { get; set; }
        public virtual Prioridades Prioridades { get; set; }
        public virtual Tareas Tareas { get; set; }
        public virtual TiposMantenimientos TiposMantenimientos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
