//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIMIRAI_Construcciones.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refacciones
    {
        public int idRefacciones { get; set; }
        public Nullable<int> idfRevisiones { get; set; }
        public Nullable<int> idfUnidades { get; set; }
        public string nombreRefaccion { get; set; }
        public Nullable<int> idfDescripcionPrioridades { get; set; }
        public Nullable<int> cantidad { get; set; }
        public string observaciones { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public int numeroReporte { get; set; }
        public string descripcion { get; set; }
    
        public virtual Revisiones Revisiones { get; set; }
        public virtual Unidades Unidades { get; set; }
        public virtual Prioridades Prioridades { get; set; }
    }
}
