//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiMIRAI_Construcciones.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revisiones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Revisiones()
        {
            this.DetallesPreventivos = new HashSet<DetallesPreventivos>();
            this.Refacciones = new HashSet<Refacciones>();
        }
    
        public int idRevisiones { get; set; }
        public Nullable<int> idfTiposMantenimientos { get; set; }
        public Nullable<int> idfEquipos { get; set; }
        public Nullable<int> idfUsuarios { get; set; }
        public Nullable<int> idfEmpresas { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesPreventivos> DetallesPreventivos { get; set; }
        public virtual Empresas Empresas { get; set; }
        public virtual Equipos Equipos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Refacciones> Refacciones { get; set; }
        public virtual TiposMantenimientos TiposMantenimientos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
