//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIMIRAI_Construcciones.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tareas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tareas()
        {
            this.Recordatorios = new HashSet<Recordatorios>();
        }
    
        public int idTareas { get; set; }
        public Nullable<int> idTiposMantenimientos { get; set; }
        public string descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recordatorios> Recordatorios { get; set; }
        public virtual TiposMantenimientos TiposMantenimientos { get; set; }
    }
}
